name: Omniscient Reborn
description: 'Расширенные уведомления о статусе, прочтении сообщений, наборе текста и изменении профиля для выбранных пользователей.'
id: notifcont
version: 2.0.0-beta
author: '@mrneoner & @neo_plugin'
app_version: '>=12.0.0'
sdk_version: '>=1.4.0'
elyx_version: '>=0.9.0'
icon: sekaiware/1
compiled: false
